import React from "react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SessionDetail } from "../(routes)/dashboard/medical-agent/[sessionId]/page";
import moment from "moment";

type Props = {
  record: SessionDetail;
};

function ViewReportDialog({ record }: Props) {
  return (
    <Dialog>
      <DialogTrigger>
        <Button variant="link" size="sm">
          View Report
        </Button>
      </DialogTrigger>

      <DialogContent
        className="max-w-3xl max-h-[85vh] overflow-y-auto"
        style={{ scrollbarWidth: "none", msOverflowStyle: "none" }}
      >
        <DialogHeader>
          <DialogTitle className="text-center text-3xl font-bold text-blue-600">
            Medical AI Voice Agent Report
          </DialogTitle>
        </DialogHeader>

        <div className="mt-6 space-y-6 text-sm text-gray-700">
          {/* Session Info */}
          <section>
            <h3 className="text-lg font-semibold text-blue-500 border-b pb-1">
              Session Info
            </h3>
            <div className="grid grid-cols-2 gap-4 mt-3">
              <p>
                <span className="font-semibold">Doctor:</span>{" "}
                {record.selectedDoctor?.specialist}
              </p>
              <p>
                <span className="font-semibold">User:</span> Anonymous
              </p>
              <p>
                <span className="font-semibold">Consulted On:</span>{" "}
                {moment(record.createdOn).format("MMMM Do YYYY, h:mm a")}
              </p>
              <p>
                <span className="font-semibold">Agent:</span> General Physician
                AI
              </p>
            </div>
          </section>

          {/* Chief Complaint */}
          <section>
            <h3 className="text-lg font-semibold text-blue-500 border-b pb-1">
              Chief Complaint
            </h3>
            <p className="mt-2">{record.notes || "Not specified"}</p>
          </section>

          {/* Summary */}
          <section>
            <h3 className="text-lg font-semibold text-blue-500 border-b pb-1">
              Summary
            </h3>
            <p className="mt-2">{record.summary || "No summary available"}</p>
          </section>

          {/* Symptoms */}
          <section>
            <h3 className="text-lg font-semibold text-blue-500 border-b pb-1">
              Symptoms
            </h3>
            <ul className="list-disc ml-5 mt-2">
              {record.symptoms?.length ? (
                record.symptoms.map((s, i) => <li key={i}>{s}</li>)
              ) : (
                <li>Not specified</li>
              )}
            </ul>
          </section>

          {/* Duration & Severity */}
          <section>
            <h3 className="text-lg font-semibold text-blue-500 border-b pb-1">
              Duration & Severity
            </h3>
            <div className="grid grid-cols-2 gap-4 mt-2">
              <p>
                <span className="font-semibold">Duration:</span>{" "}
                {record.duration || "Not specified"}
              </p>
              <p>
                <span className="font-semibold">Severity:</span>{" "}
                {record.severity || "Moderate"}
              </p>
            </div>
          </section>

          {/* Medications */}
          <section>
            <h3 className="text-lg font-semibold text-blue-500 border-b pb-1">
              Medications Mentioned
            </h3>
            <ul className="list-disc ml-5 mt-2">
              {record.medications?.length ? (
                record.medications.map((m, i) => <li key={i}>{m}</li>)
              ) : (
                <>
                  <li>ibuprofen</li>
                  <li>acetaminophen</li>
                </>
              )}
            </ul>
          </section>

          {/* Recommendations */}
          <section>
            <h3 className="text-lg font-semibold text-blue-500 border-b pb-1">
              Recommendations
            </h3>
            <ul className="list-disc ml-5 mt-2">
              <li>
                Try over-the-counter pain relievers (ibuprofen or acetaminophen)
              </li>
              <li>Follow dosage instructions carefully</li>
              <li>Consult a healthcare provider if pain persists or worsens</li>
            </ul>
          </section>

          {/* Disclaimer */}
          <div className="mt-6 border-t pt-3 text-xs text-center text-gray-500">
            This report was generated by an AI Medical Assistant for
            informational purposes only.
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default ViewReportDialog;
